export default {
    en: {
        features : {
            new: "New",
            f1: "Shape editor",
            f2: "Change shape order",
            f3: "Add text",
            f4: "Multiple screens",
            f5: "Add actions",
        },
        code_shower: {
            generated_code: "Generated code",
            copied: "Code copied to clipboard",
            copy: "Copy code to clipboard"
        },
        canva_select: {
            screenX: "Screen no."
        },
        shapes: {
            rectangle: "Rectangle",
            circle: "Circle",
            triangle: "Triangle",
            text: "Texte",
        },
        editor: {
            moveshift: "You can press SHIFT while moving the shape to snap it to grid.",
            bringtofront: "Bring to front",
            bringforward: "Bring forward",
            sendbackwards: "Send backward",
            sendtoback: "Send to back",
            unselect: "Unselect"
        },
        actions: {
            title: "Actions",
            add: "Add an action",
            addtip: "Add a new action that will be executed when the object is pressed",
            added: "Action added",
            noActions: "No actions",
            removeObjctNbr: "Remove object with index:",
            changeTextNbr: "Change the text at index:",
            changeTextTo: "Remplace text with:",
            moveObjctNbr: "Move object with index:",
            newPos: "New object position",
            gotoScreen: "Goto to screen no.",
            type: {
                remove: "Remove an objet",
                changeText: "Change object text content",
                move: "Move an object",
                switchScreen: "Switch screen",
            },
        },
        objectX: "Object no.",
        add: "Add",
        newText: "New text",
        position: "Position",
        points: "Points",
        size: "Size",
        fontSize: "Text size",
        alignment: "Alignment",
        radii: "Radii",
        width: "Width",
        height: "Height",
        thickness: "Epaisseur",
        color: "Color",
        fill: "Fill",
    },
    fr: {
        features : {
            new: "Nouveau",
            f1: "Editeur de formes",
            f2: "Changer l'ordre des objects",
            f3: "Ajouter du texte",
            f4: "Écrans multiples",
            f5: "Ajouter des actions",
        },
        code_shower: {
            generated_code: "Code généré",
            copied: "Code copié dans le presse-papiers",
            copy: "Copier le code dans le presse-papiers"
        },
        canva_select: {
            screenX: "Écran n°"
        },
        shapes: {
            rectangle: "Rectangle",
            circle: "Cercle",
            triangle: "Triangle",
            text: "Texte",
        },
        editor: {
            moveshift: "Vous pouvez appuyer sur SHIFT tout en déplaçant l'objet pour l'aligner sur la grille.",
            bringtofront: "Mettre au premier plan",
            bringforward: "Avancer",
            sendbackwards: "Reculer",
            sendtoback: "Envoyer à l'arrière plan",
            unselect: "Désélectionner"
        },
        actions: {
            title: "Actions",
            add: "Ajouter une action",
            addtip: "Ajoute une action qui sera executée quand on appuyera sur l'objet",
            added: "Action ajoutée",
            noActions: "Aucune action",
            removeObjctNbr: "Enlever l'object avec l'indice:",
            changeTextNbr: "Changer le texte à l'indice:",
            changeTextTo: "Remplacer le texte par:",
            moveObjctNbr: "Déplacer l'objet à l'indice:",
            newPos: "Nouvelle position de l'objet",
            gotoScreen: "Aller sur l'écran n°",
            type: {
                remove: "Enlever un objet",
                changeText: "Change le contenu d'un texte",
                move: "Bouger un objet",
                switchScreen: "Changer d'écran",
            },
        },
        objectX: "Objet n°",
        add: "Ajouter",
        newText: "Nouveau texte",
        position: "Position",
        points: "Points",
        size: "Taille",
        fontSize: "Taille du texte",
        alignment: "Alignement",
        radii: "Rayons",
        width: "Largeur",
        height: "Hauteur",
        thickness: "Epaisseur",
        color: "Couleur",
        fill: "Remplir",
    }
}
